CREATE TABLE "leases" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"make" varchar(100) NOT NULL,
	"model" varchar(100) NOT NULL,
	"year" integer NOT NULL,
	"msrp" numeric(10, 2) NOT NULL,
	"net_cap_cost" numeric(10, 2) NOT NULL,
	"residual_value" numeric(10, 2) NOT NULL,
	"residual_percent" numeric(5, 2) NOT NULL,
	"money_factor" numeric(10, 6) NOT NULL,
	"monthly_payment" numeric(10, 2) NOT NULL,
	"down_payment" numeric(10, 2) NOT NULL,
	"disposition_fee" numeric(10, 2) NOT NULL,
	"purchase_fee" numeric(10, 2) NOT NULL,
	"term_months" integer NOT NULL,
	"months_elapsed" integer NOT NULL,
	"allowed_miles_per_year" integer NOT NULL,
	"overage_fee_per_mile" numeric(6, 4) NOT NULL,
	"current_mileage" integer NOT NULL,
	"mileage_date" date NOT NULL,
	"state_code" varchar(2) NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
